title: Ils vont s'empiler !
author: BS
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  It is my website, ready to fly.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
